/** Created by xwp on 2021-12-13 **/
export default {
  'text': {
    name: '参数',
    paramType: 'text',
    isRequired: true,
    style: 'bottom',
    layout: 'dropdown',
    defaultValue: '',
    options: [],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      size: ['fixed', {
        width: 148,
        height: 17
      }],
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
  },
  'radio': {
    name: '参数',
    paramType: 'radio',
    isRequired: true,
    style: 'all',
    layout: 'dropdown',
    defaultValue: '',
    options: ['请输入选项名称'],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
  },
  'checkbox': {
    name: '参数',
    paramType: 'checkbox',
    isRequired: true,
    style: 'all',
    layout: 'dropdown',
    defaultValue: '',
    options: ['请输入选项名称'],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
  },
  'image': {
    name: '参数',
    paramType: 'image',
    description: '',
    isRequired: true,
  },
  'date': {
    name: '参数',
    paramType: 'date',
    format: 'yyyy-MM-dd',
    isRequired: true,
    style: 'bottom',
    layout: 'dropdown',
    defaultValue: '',
    options: [],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      size: ['fixed', {
        width: 148,
        height: 17
      }],
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
  },
  'idcard': {
    name: '参数',
    paramType: 'idcard',
    isRequired: true,
    style: 'bottom',
    layout: 'dropdown',
    defaultValue: '',
    options: [],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      size: ['fixed', {
        width: 148,
        height: 17
      }],
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
  },
  'table': {
    name: 'table',
    paramType: 'table',
    isRequired: false,
    style: 'bottom',
    layout: 'dropdown',
    defaultValue: '',
    options: [],
    description: '',
    fontConfig: {
      fontFamily: 'none',
      fontSize: 'none',
      fontWeight: 'inherit',
      justifyContent: 'flex-start',
      size: ['fixed', {
        width: 148,
        height: 17
      }],
      color: null,
    },
    maxLength: 1000,
    columnKeys: [],
    hideThead: false,
  },
}
